version: '3'

services:
  sql2022:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: your_strong_password  # Replace with a strong password
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql/data

volumes:
  sql_data: {}
# # PostgreSQL container
# postgres:
#   image: postgres:latest
#   environment:
#     POSTGRES_PASSWORD: 'your_strong_password' # Replace with a strong password
#   ports:
#     - "5432:5432"  # Map container port 5432 to host port 5432
#   volumes:
#     - postgres_data:/var/lib/postgresql/data  # Persistent storage for database data

#volumes:
# # Persistent volume for PostgreSQL data
#   postgres_data: {}